all: stopper executer runner backgrounder

stopper: stopper.c

executer: executer.c

runner: runner.c

backgrounder: backgrounder.c

clean:
	rm -rf stopper
	rm -rf executer 
	rm -rf runner
	rm -rf backgrounder
